In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv("m.csv")

In [6]:
df.head()

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,...,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
0,Group stage,1,Thu,2026-06-11,13:00,Mexico,South Africa,2–0,2,0,...,11,3,1,12,8,8,7,1.0,1.0,NaN
1,Group stage,1,Thu,2026-06-11,20:00,Korea Republic,Czechia,2–1,2,1,...,16,4,5,12,15,11,7,2.0,2.0,NaN
2,Group stage,1,Fri,2026-06-12,15:00,Canada,Bosnia & Herz.,1–1,1,1,...,20,9,4,24,10,4,10,1.0,0.0,NaN
3,Group stage,1,Fri,2026-06-12,18:00,United States,Paraguay,4–1,4,1,...,17,3,1,17,5,11,9,2.0,1.0,NaN
4,Group stage,1,Sat,2026-06-13,12:00,Qatar,Switzerland,1–1,1,1,...,11,3,10,8,35,10,7,0.0,1.0,NaN

In [7]:
df.tail()

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,...,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
31,Group stage,2,Fri,2026-06-19,20:30,Brazil,Haiti,3–0,3,0,...,14,4,4,9,11,10,9,8.0,4.0,NaN
32,Group stage,2,Sat,2026-06-20,12:00,Netherlands,Sweden,5–1,5,1,...,12,2,5,15,21,8,6,3.0,3.0,NaN
33,Group stage,2,Sat,2026-06-20,16:00,Germany,Côte d'Ivoire,2–1,2,1,...,7,8,3,21,9,7,13,0.0,1.0,NaN
34,Group stage,2,Sat,2026-06-20,19:00,Ecuador,Curaçao,0–0,0,0,...,10,9,0,32,1,7,8,1.0,2.0,NaN
35,Group stage,2,Sat,2026-06-20,22:00,Tunisia,Japan,0–4,0,4,...,15,3,5,10,11,14,6,1.0,1.0,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 42 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   round               36 non-null     object
 1   gameweek            36 non-null     int64
 2   dayofweek           36 non-null     object
 3   date                36 non-null     object
 4   start_time          36 non-null     object
 5   home_team           36 non-null     object
 6   away_team           36 non-null     object
 7   score               36 non-null     object
 8   home_score          36 non-null     int64
 9   away_score          36 non-null     int64
 10  attendance          36 non-null     object
 11  venue               36 non-null     object
 12  referee             36 non-null     object
 13  home_formation      36 non-null     object
 14  away_formation      36 non-null     object
 15  home_manager        36 non-null     object
 16  away_manager        36 non-null     object
 17  home_captain        36 non-null     object
 18  away_captain        36 non-null     object
 19  home_possession     36 non-null     int64
 20  away_possession     36 non-null     int64
 21  home_sot            36 non-null     int64
 22  away_sot            36 non-null     int64
 23  home_total_shots    36 non-null     int64
 24  away_total_shots    36 non-null     int64
 25  home_saves          36 non-null     int64
 26  away_saves          36 non-null     int64
 27  home_cards_yellow   36 non-null     int64
 28  away_cards_yellow   36 non-null     int64
 29  home_cards_red      36 non-null     int64
 30  away_cards_red      36 non-null     int64
 31  home_fouls          36 non-null     int64
 32  away_fouls          36 non-null     int64
 33  home_corners        36 non-null     int64
 34  away_corners        36 non-null     int64
 35  home_crosses        36 non-null     int64
 36  away_crosses        36 non-null     int64
 37  home_interceptions  36 non-null     int64
 38  away_interceptions  36 non-null     int64
 39  home_offsides       35 non-null     float64
 40  away_offsides       35 non-null     float64
 41  notes               0 non-null      float64
dtypes: float64(3), int64(23), object(16)
memory usage: 11.9+ KB

In [9]:
df.isnull

<bound method DataFrame.isnull of           round  gameweek dayofweek        date start_time       home_team  \
0   Group stage         1       Thu  2026-06-11      13:00          Mexico
1   Group stage         1       Thu  2026-06-11      20:00  Korea Republic
2   Group stage         1       Fri  2026-06-12      15:00          Canada
3   Group stage         1       Fri  2026-06-12      18:00   United States
4   Group stage         1       Sat  2026-06-13      12:00           Qatar
5   Group stage         1       Sat  2026-06-13      18:00          Brazil
6   Group stage         1       Sat  2026-06-13      21:00           Haiti
7   Group stage         1       Sat  2026-06-13      21:00       Australia
8   Group stage         1       Sun  2026-06-14      12:00         Germany
9   Group stage         1       Sun  2026-06-14      15:00     Netherlands
10  Group stage         1       Sun  2026-06-14      19:00   Côte d'Ivoire
11  Group stage         1       Sun  2026-06-14      20:00          Sweden
12  Group stage         1       Mon  2026-06-15      12:00         Belgium
13  Group stage         1       Mon  2026-06-15      12:00           Spain
14  Group stage         1       Mon  2026-06-15      18:00         IR Iran
15  Group stage         1       Mon  2026-06-15      18:00    Saudi Arabia
16  Group stage         1       Tue  2026-06-16      15:00          France
17  Group stage         1       Tue  2026-06-16      18:00            Iraq
18  Group stage         1       Tue  2026-06-16      20:00       Argentina
19  Group stage         1       Tue  2026-06-16      21:00         Austria
20  Group stage         1       Wed  2026-06-17      12:00        Portugal
21  Group stage         1       Wed  2026-06-17      15:00         England
22  Group stage         1       Wed  2026-06-17      19:00           Ghana
23  Group stage         1       Wed  2026-06-17      20:00      Uzbekistan
24  Group stage         2       Thu  2026-06-18      12:00         Czechia
25  Group stage         2       Thu  2026-06-18      12:00     Switzerland
26  Group stage         2       Thu  2026-06-18      15:00          Canada
27  Group stage         2       Thu  2026-06-18      19:00          Mexico
28  Group stage         2       Fri  2026-06-19      12:00   United States
29  Group stage         2       Fri  2026-06-19      18:00        Scotland
30  Group stage         2       Fri  2026-06-19      20:00         Türkiye
31  Group stage         2       Fri  2026-06-19      20:30          Brazil
32  Group stage         2       Sat  2026-06-20      12:00     Netherlands
33  Group stage         2       Sat  2026-06-20      16:00         Germany
34  Group stage         2       Sat  2026-06-20      19:00         Ecuador
35  Group stage         2       Sat  2026-06-20      22:00         Tunisia

         away_team score  home_score  away_score  ... away_fouls home_corners  \
0     South Africa   2–0           2           0  ...         11            3
1          Czechia   2–1           2           1  ...         16            4
2   Bosnia & Herz.   1–1           1           1  ...         20            9
3         Paraguay   4–1           4           1  ...         17            3
4      Switzerland   1–1           1           1  ...         11            3
5          Morocco   1–1           1           1  ...         14            6
6         Scotland   0–1           0           1  ...         21            4
7          Türkiye   2–0           2           0  ...          4            5
8          Curaçao   7–1           7           1  ...         11            8
9            Japan   2–2           2           2  ...          7            5
10         Ecuador   1–0           1           0  ...         13            3
11         Tunisia   5–1           5           1  ...          8            4
12           Egypt   1–1           1           1  ...         15            2
13      Cabo Verde   0–0           0           0  ...          1           11
14     New Zealand   2–2           2           2  ...          8            4
15         Uruguay   1–1           1           1  ...          6            4
16         Senegal   3–1           3           1  ...          9            6
17          Norway   1–4           1           4  ...         13            2
18         Algeria   3–0           3           0  ...          8            2
19          Jordan   3–1           3           1  ...          7            4
20        Congo DR   1–1           1           1  ...         10            5
21         Croatia   4–2           4           2  ...         12            8
22          Panama   1–0           1           0  ...         11            2
23        Colombia   1–3           1           3  ...         11            3
24    South Africa   1–1           1           1  ...         10            5
25  Bosnia & Herz.   4–1           4           1  ...         18            7
26           Qatar   6–0           6           0  ...         10           19
27  Korea Republic   1–0           1           0  ...          7            0
28       Australia   2–0           2           0  ...         16            7
29         Morocco   0–1           0           1  ...          8            2
30        Paraguay   0–1           0           1  ...         15           12
31           Haiti   3–0           3           0  ...         14            4
32          Sweden   5–1           5           1  ...         12            2
33   Côte d'Ivoire   2–1           2           1  ...          7            8
34         Curaçao   0–0           0           0  ...         10            9
35           Japan   0–4           0           4  ...         15            3

   away_corners home_crosses away_crosses home_interceptions  \
0             1           12            8                  8
1             5           12           15                 11
2             4           24           10                  4
3             1           17            5                 11
4            10            8           35                 10
5             2           16           15                  5
6             3           23           14                  6
7             8           14           26                  6
8             1           12            7                 10
9             4           21           23                  7
10            5            7           14                 11
11            2           12           13                  8
12            7           16           13                 10
13            1           36            4                  6
14            1           19           12                 11
15           14            7           47                  7
16            4            9            9                  7
17            5           13           17                  5
18            2            5            8                 12
19            3           17           15                 15
20            4           23            9                  2
21            2           13           13                  7
22            2           16           21                  8
23            4           13           15                  7
24            5           16           17                  9
25            3           22           12                  4
26            1           55            3                  6
27            2            5            9                  7
28            4           14           19                 21
29            5           13           10                  9
30            0           42            6                  6
31            4            9           11                 10
32            5           15           21                  8
33            3           21            9                  7
34            0           32            1                  7
35            5           10           11                 14

   away_interceptions home_offsides away_offsides  notes
0                   7           1.0           1.0    NaN
1                   7           2.0           2.0    NaN
2                  10           1.0           0.0    NaN
3                   9           2.0           1.0    NaN
4                   7           0.0           1.0    NaN
5                   4           0.0           1.0    NaN
6                   6           3.0           1.0    NaN
7                   4           1.0           3.0    NaN
8                  16           0.0           1.0    NaN
9                   4           1.0           0.0    NaN
10                 13           NaN           NaN    NaN
11                  5           3.0           6.0    NaN
12                 12           0.0           1.0    NaN
13                 16           2.0           3.0    NaN
14                 13           2.0           0.0    NaN
15                 10           0.0           6.0    NaN
16                  8           1.0           3.0    NaN
17                  3           1.0           0.0    NaN
18                  8           3.0           1.0    NaN
19                 12           3.0           1.0    NaN
20                  5           3.0           2.0    NaN
21                  7           0.0           1.0    NaN
22                  5           4.0           1.0    NaN
23                  6           0.0           3.0    NaN
24                  9           2.0           3.0    NaN
25                 12           3.0           1.0    NaN
26                 11           1.0           1.0    NaN
27                  5           3.0           6.0    NaN
28                  7           1.0           0.0    NaN
29                  5           1.0           0.0    NaN
30                  9           2.0           3.0    NaN
31                  9           8.0           4.0    NaN
32                  6           3.0           3.0    NaN
33                 13           0.0           1.0    NaN
34                  8           1.0           2.0    NaN
35                  6           1.0           1.0    NaN

[36 rows x 42 columns]>

In [11]:
df.isnull().sum()

round                  0
gameweek               0
dayofweek              0
date                   0
start_time             0
home_team              0
away_team              0
score                  0
home_score             0
away_score             0
attendance             0
venue                  0
referee                0
home_formation         0
away_formation         0
home_manager           0
away_manager           0
home_captain           0
away_captain           0
home_possession        0
away_possession        0
home_sot               0
away_sot               0
home_total_shots       0
away_total_shots       0
home_saves             0
away_saves             0
home_cards_yellow      0
away_cards_yellow      0
home_cards_red         0
away_cards_red         0
home_fouls             0
away_fouls             0
home_corners           0
away_corners           0
home_crosses           0
away_crosses           0
home_interceptions     0
away_interceptions     0
home_offsides          1
away_offsides          1
notes                 36
dtype: int64

In [12]:
df.notnull()

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,...,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
5,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
6,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
7,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
8,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
9,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
10,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,False,False,False
11,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
12,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
13,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
14,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
15,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
16,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
17,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
18,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
19,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
20,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
21,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
22,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
23,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
24,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
25,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
26,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
27,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
28,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
29,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
30,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
31,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
32,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
33,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
34,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
35,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False

In [13]:
df.describe()

,gameweek,home_score,away_score,home_possession,away_possession,home_sot,away_sot,home_total_shots,away_total_shots,home_saves,...,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,...,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,35.000000,35.000000,0.0
mean,1.333333,2.027778,1.000000,53.777778,46.305556,5.027778,3.388889,13.861111,10.916667,2.416667,...,11.277778,5.222222,3.666667,17.194444,13.805556,8.388889,8.250000,1.685714,1.828571,NaN
std,0.478091,1.780628,1.014185,13.627936,13.593737,3.299230,2.345546,7.251218,6.212315,2.156386,...,4.379244,3.618296,2.818307,10.380805,8.808501,3.515499,3.417392,1.604615,1.688816,NaN
min,1.000000,0.000000,0.000000,28.000000,21.000000,0.000000,0.000000,2.000000,2.000000,0.000000,...,1.000000,0.000000,0.000000,5.000000,1.000000,2.000000,3.000000,0.000000,0.000000,NaN
25%,1.000000,1.000000,0.000000,41.750000,38.000000,3.000000,2.000000,8.750000,7.000000,1.000000,...,8.000000,3.000000,2.000000,12.000000,9.000000,6.000000,5.750000,1.000000,1.000000,NaN
50%,1.000000,1.500000,1.000000,54.000000,46.000000,4.000000,3.000000,12.500000,9.500000,2.000000,...,11.000000,4.000000,3.500000,14.500000,12.500000,7.500000,7.500000,1.000000,1.000000,NaN
75%,2.000000,3.000000,1.000000,62.000000,58.250000,7.000000,4.000000,16.000000,12.500000,3.000000,...,14.250000,7.000000,5.000000,21.000000,15.500000,10.000000,10.250000,3.000000,3.000000,NaN
max,2.000000,7.000000,4.000000,79.000000,72.000000,15.000000,10.000000,32.000000,30.000000,9.000000,...,21.000000,19.000000,14.000000,55.000000,47.000000,21.000000,16.000000,8.000000,6.000000,NaN

In [15]:
df.columns

Index(['round', 'gameweek', 'dayofweek', 'date', 'start_time', 'home_team',
       'away_team', 'score', 'home_score', 'away_score', 'attendance', 'venue',
       'referee', 'home_formation', 'away_formation', 'home_manager',
       'away_manager', 'home_captain', 'away_captain', 'home_possession',
       'away_possession', 'home_sot', 'away_sot', 'home_total_shots',
       'away_total_shots', 'home_saves', 'away_saves', 'home_cards_yellow',
       'away_cards_yellow', 'home_cards_red', 'away_cards_red', 'home_fouls',
       'away_fouls', 'home_corners', 'away_corners', 'home_crosses',
       'away_crosses', 'home_interceptions', 'away_interceptions',
       'home_offsides', 'away_offsides', 'notes'],
      dtype='object')

In [16]:
df.shape

(36, 42)

In [17]:
df["away_crosses"].mean()

np.float64(13.805555555555555)

In [18]:
df["away_crosses"].median()

12.5

In [19]:
df["away_crosses"].mode()

0     9
1    15
Name: away_crosses, dtype: int64

In [20]:
df["away_crosses"].max()

47

In [21]:
df["away_crosses"].min()

1

In [22]:
df["away_crosses"].sum()

np.int64(497)

In [23]:
df["away_crosses"].count()

np.int64(36)

In [24]:
df["away_crosses"].std()

8.808500584076869

In [25]:
df.fillna(0)

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,...,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
0,Group stage,1,Thu,2026-06-11,13:00,Mexico,South Africa,2–0,2,0,...,11,3,1,12,8,8,7,1.0,1.0,0.0
1,Group stage,1,Thu,2026-06-11,20:00,Korea Republic,Czechia,2–1,2,1,...,16,4,5,12,15,11,7,2.0,2.0,0.0
2,Group stage,1,Fri,2026-06-12,15:00,Canada,Bosnia & Herz.,1–1,1,1,...,20,9,4,24,10,4,10,1.0,0.0,0.0
3,Group stage,1,Fri,2026-06-12,18:00,United States,Paraguay,4–1,4,1,...,17,3,1,17,5,11,9,2.0,1.0,0.0
4,Group stage,1,Sat,2026-06-13,12:00,Qatar,Switzerland,1–1,1,1,...,11,3,10,8,35,10,7,0.0,1.0,0.0
5,Group stage,1,Sat,2026-06-13,18:00,Brazil,Morocco,1–1,1,1,...,14,6,2,16,15,5,4,0.0,1.0,0.0
6,Group stage,1,Sat,2026-06-13,21:00,Haiti,Scotland,0–1,0,1,...,21,4,3,23,14,6,6,3.0,1.0,0.0
7,Group stage,1,Sat,2026-06-13,21:00,Australia,Türkiye,2–0,2,0,...,4,5,8,14,26,6,4,1.0,3.0,0.0
8,Group stage,1,Sun,2026-06-14,12:00,Germany,Curaçao,7–1,7,1,...,11,8,1,12,7,10,16,0.0,1.0,0.0
9,Group stage,1,Sun,2026-06-14,15:00,Netherlands,Japan,2–2,2,2,...,7,5,4,21,23,7,4,1.0,0.0,0.0
10,Group stage,1,Sun,2026-06-14,19:00,Côte d'Ivoire,Ecuador,1–0,1,0,...,13,3,5,7,14,11,13,0.0,0.0,0.0
11,Group stage,1,Sun,2026-06-14,20:00,Sweden,Tunisia,5–1,5,1,...,8,4,2,12,13,8,5,3.0,6.0,0.0
12,Group stage,1,Mon,2026-06-15,12:00,Belgium,Egypt,1–1,1,1,...,15,2,7,16,13,10,12,0.0,1.0,0.0
13,Group stage,1,Mon,2026-06-15,12:00,Spain,Cabo Verde,0–0,0,0,...,1,11,1,36,4,6,16,2.0,3.0,0.0
14,Group stage,1,Mon,2026-06-15,18:00,IR Iran,New Zealand,2–2,2,2,...,8,4,1,19,12,11,13,2.0,0.0,0.0
15,Group stage,1,Mon,2026-06-15,18:00,Saudi Arabia,Uruguay,1–1,1,1,...,6,4,14,7,47,7,10,0.0,6.0,0.0
16,Group stage,1,Tue,2026-06-16,15:00,France,Senegal,3–1,3,1,...,9,6,4,9,9,7,8,1.0,3.0,0.0
17,Group stage,1,Tue,2026-06-16,18:00,Iraq,Norway,1–4,1,4,...,13,2,5,13,17,5,3,1.0,0.0,0.0
18,Group stage,1,Tue,2026-06-16,20:00,Argentina,Algeria,3–0,3,0,...,8,2,2,5,8,12,8,3.0,1.0,0.0
19,Group stage,1,Tue,2026-06-16,21:00,Austria,Jordan,3–1,3,1,...,7,4,3,17,15,15,12,3.0,1.0,0.0
20,Group stage,1,Wed,2026-06-17,12:00,Portugal,Congo DR,1–1,1,1,...,10,5,4,23,9,2,5,3.0,2.0,0.0
21,Group stage,1,Wed,2026-06-17,15:00,England,Croatia,4–2,4,2,...,12,8,2,13,13,7,7,0.0,1.0,0.0
22,Group stage,1,Wed,2026-06-17,19:00,Ghana,Panama,1–0,1,0,...,11,2,2,16,21,8,5,4.0,1.0,0.0
23,Group stage,1,Wed,2026-06-17,20:00,Uzbekistan,Colombia,1–3,1,3,...,11,3,4,13,15,7,6,0.0,3.0,0.0
24,Group stage,2,Thu,2026-06-18,12:00,Czechia,South Africa,1–1,1,1,...,10,5,5,16,17,9,9,2.0,3.0,0.0
25,Group stage,2,Thu,2026-06-18,12:00,Switzerland,Bosnia & Herz.,4–1,4,1,...,18,7,3,22,12,4,12,3.0,1.0,0.0
26,Group stage,2,Thu,2026-06-18,15:00,Canada,Qatar,6–0,6,0,...,10,19,1,55,3,6,11,1.0,1.0,0.0
27,Group stage,2,Thu,2026-06-18,19:00,Mexico,Korea Republic,1–0,1,0,...,7,0,2,5,9,7,5,3.0,6.0,0.0
28,Group stage,2,Fri,2026-06-19,12:00,United States,Australia,2–0,2,0,...,16,7,4,14,19,21,7,1.0,0.0,0.0
29,Group stage,2,Fri,2026-06-19,18:00,Scotland,Morocco,0–1,0,1,...,8,2,5,13,10,9,5,1.0,0.0,0.0
30,Group stage,2,Fri,2026-06-19,20:00,Türkiye,Paraguay,0–1,0,1,...,15,12,0,42,6,6,9,2.0,3.0,0.0
31,Group stage,2,Fri,2026-06-19,20:30,Brazil,Haiti,3–0,3,0,...,14,4,4,9,11,10,9,8.0,4.0,0.0
32,Group stage,2,Sat,2026-06-20,12:00,Netherlands,Sweden,5–1,5,1,...,12,2,5,15,21,8,6,3.0,3.0,0.0
33,Group stage,2,Sat,2026-06-20,16:00,Germany,Côte d'Ivoire,2–1,2,1,...,7,8,3,21,9,7,13,0.0,1.0,0.0
34,Group stage,2,Sat,2026-06-20,19:00,Ecuador,Curaçao,0–0,0,0,...,10,9,0,32,1,7,8,1.0,2.0,0.0
35,Group stage,2,Sat,2026-06-20,22:00,Tunisia,Japan,0–4,0,4,...,15,3,5,10,11,14,6,1.0,1.0,0.0

In [26]:
df.fillna("unknown")

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,...,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
0,Group stage,1,Thu,2026-06-11,13:00,Mexico,South Africa,2–0,2,0,...,11,3,1,12,8,8,7,1.0,1.0,unknown
1,Group stage,1,Thu,2026-06-11,20:00,Korea Republic,Czechia,2–1,2,1,...,16,4,5,12,15,11,7,2.0,2.0,unknown
2,Group stage,1,Fri,2026-06-12,15:00,Canada,Bosnia & Herz.,1–1,1,1,...,20,9,4,24,10,4,10,1.0,0.0,unknown
3,Group stage,1,Fri,2026-06-12,18:00,United States,Paraguay,4–1,4,1,...,17,3,1,17,5,11,9,2.0,1.0,unknown
4,Group stage,1,Sat,2026-06-13,12:00,Qatar,Switzerland,1–1,1,1,...,11,3,10,8,35,10,7,0.0,1.0,unknown
5,Group stage,1,Sat,2026-06-13,18:00,Brazil,Morocco,1–1,1,1,...,14,6,2,16,15,5,4,0.0,1.0,unknown
6,Group stage,1,Sat,2026-06-13,21:00,Haiti,Scotland,0–1,0,1,...,21,4,3,23,14,6,6,3.0,1.0,unknown
7,Group stage,1,Sat,2026-06-13,21:00,Australia,Türkiye,2–0,2,0,...,4,5,8,14,26,6,4,1.0,3.0,unknown
8,Group stage,1,Sun,2026-06-14,12:00,Germany,Curaçao,7–1,7,1,...,11,8,1,12,7,10,16,0.0,1.0,unknown
9,Group stage,1,Sun,2026-06-14,15:00,Netherlands,Japan,2–2,2,2,...,7,5,4,21,23,7,4,1.0,0.0,unknown
10,Group stage,1,Sun,2026-06-14,19:00,Côte d'Ivoire,Ecuador,1–0,1,0,...,13,3,5,7,14,11,13,unknown,unknown,unknown
11,Group stage,1,Sun,2026-06-14,20:00,Sweden,Tunisia,5–1,5,1,...,8,4,2,12,13,8,5,3.0,6.0,unknown
12,Group stage,1,Mon,2026-06-15,12:00,Belgium,Egypt,1–1,1,1,...,15,2,7,16,13,10,12,0.0,1.0,unknown
13,Group stage,1,Mon,2026-06-15,12:00,Spain,Cabo Verde,0–0,0,0,...,1,11,1,36,4,6,16,2.0,3.0,unknown
14,Group stage,1,Mon,2026-06-15,18:00,IR Iran,New Zealand,2–2,2,2,...,8,4,1,19,12,11,13,2.0,0.0,unknown
15,Group stage,1,Mon,2026-06-15,18:00,Saudi Arabia,Uruguay,1–1,1,1,...,6,4,14,7,47,7,10,0.0,6.0,unknown
16,Group stage,1,Tue,2026-06-16,15:00,France,Senegal,3–1,3,1,...,9,6,4,9,9,7,8,1.0,3.0,unknown
17,Group stage,1,Tue,2026-06-16,18:00,Iraq,Norway,1–4,1,4,...,13,2,5,13,17,5,3,1.0,0.0,unknown
18,Group stage,1,Tue,2026-06-16,20:00,Argentina,Algeria,3–0,3,0,...,8,2,2,5,8,12,8,3.0,1.0,unknown
19,Group stage,1,Tue,2026-06-16,21:00,Austria,Jordan,3–1,3,1,...,7,4,3,17,15,15,12,3.0,1.0,unknown
20,Group stage,1,Wed,2026-06-17,12:00,Portugal,Congo DR,1–1,1,1,...,10,5,4,23,9,2,5,3.0,2.0,unknown
21,Group stage,1,Wed,2026-06-17,15:00,England,Croatia,4–2,4,2,...,12,8,2,13,13,7,7,0.0,1.0,unknown
22,Group stage,1,Wed,2026-06-17,19:00,Ghana,Panama,1–0,1,0,...,11,2,2,16,21,8,5,4.0,1.0,unknown
23,Group stage,1,Wed,2026-06-17,20:00,Uzbekistan,Colombia,1–3,1,3,...,11,3,4,13,15,7,6,0.0,3.0,unknown
24,Group stage,2,Thu,2026-06-18,12:00,Czechia,South Africa,1–1,1,1,...,10,5,5,16,17,9,9,2.0,3.0,unknown
25,Group stage,2,Thu,2026-06-18,12:00,Switzerland,Bosnia & Herz.,4–1,4,1,...,18,7,3,22,12,4,12,3.0,1.0,unknown
26,Group stage,2,Thu,2026-06-18,15:00,Canada,Qatar,6–0,6,0,...,10,19,1,55,3,6,11,1.0,1.0,unknown
27,Group stage,2,Thu,2026-06-18,19:00,Mexico,Korea Republic,1–0,1,0,...,7,0,2,5,9,7,5,3.0,6.0,unknown
28,Group stage,2,Fri,2026-06-19,12:00,United States,Australia,2–0,2,0,...,16,7,4,14,19,21,7,1.0,0.0,unknown
29,Group stage,2,Fri,2026-06-19,18:00,Scotland,Morocco,0–1,0,1,...,8,2,5,13,10,9,5,1.0,0.0,unknown
30,Group stage,2,Fri,2026-06-19,20:00,Türkiye,Paraguay,0–1,0,1,...,15,12,0,42,6,6,9,2.0,3.0,unknown
31,Group stage,2,Fri,2026-06-19,20:30,Brazil,Haiti,3–0,3,0,...,14,4,4,9,11,10,9,8.0,4.0,unknown
32,Group stage,2,Sat,2026-06-20,12:00,Netherlands,Sweden,5–1,5,1,...,12,2,5,15,21,8,6,3.0,3.0,unknown
33,Group stage,2,Sat,2026-06-20,16:00,Germany,Côte d'Ivoire,2–1,2,1,...,7,8,3,21,9,7,13,0.0,1.0,unknown
34,Group stage,2,Sat,2026-06-20,19:00,Ecuador,Curaçao,0–0,0,0,...,10,9,0,32,1,7,8,1.0,2.0,unknown
35,Group stage,2,Sat,2026-06-20,22:00,Tunisia,Japan,0–4,0,4,...,15,3,5,10,11,14,6,1.0,1.0,unknown

In [27]:
df["away_crosses"].fillna(df["away_crosses"].mean())

0      8
1     15
2     10
3      5
4     35
5     15
6     14
7     26
8      7
9     23
10    14
11    13
12    13
13     4
14    12
15    47
16     9
17    17
18     8
19    15
20     9
21    13
22    21
23    15
24    17
25    12
26     3
27     9
28    19
29    10
30     6
31    11
32    21
33     9
34     1
35    11
Name: away_crosses, dtype: int64

In [31]:
df["away_crosses"].fillna(df["away_crosses"].median())

0      8
1     15
2     10
3      5
4     35
5     15
6     14
7     26
8      7
9     23
10    14
11    13
12    13
13     4
14    12
15    47
16     9
17    17
18     8
19    15
20     9
21    13
22    21
23    15
24    17
25    12
26     3
27     9
28    19
29    10
30     6
31    11
32    21
33     9
34     1
35    11
Name: away_crosses, dtype: int64

In [32]:
df["away_crosses"].fillna(df["away_crosses"].mode()[0])

0      8
1     15
2     10
3      5
4     35
5     15
6     14
7     26
8      7
9     23
10    14
11    13
12    13
13     4
14    12
15    47
16     9
17    17
18     8
19    15
20     9
21    13
22    21
23    15
24    17
25    12
26     3
27     9
28    19
29    10
30     6
31    11
32    21
33     9
34     1
35    11
Name: away_crosses, dtype: int64

In [33]:
df.dtypes

round                  object
gameweek                int64
dayofweek              object
date                   object
start_time             object
home_team              object
away_team              object
score                  object
home_score              int64
away_score              int64
attendance             object
venue                  object
referee                object
home_formation         object
away_formation         object
home_manager           object
away_manager           object
home_captain           object
away_captain           object
home_possession         int64
away_possession         int64
home_sot                int64
away_sot                int64
home_total_shots        int64
away_total_shots        int64
home_saves              int64
away_saves              int64
home_cards_yellow       int64
away_cards_yellow       int64
home_cards_red          int64
away_cards_red          int64
home_fouls              int64
away_fouls              int64
home_corners            int64
away_corners            int64
home_crosses            int64
away_crosses            int64
home_interceptions      int64
away_interceptions      int64
home_offsides         float64
away_offsides         float64
notes                 float64
dtype: object

In [34]:
df[df["away_crosses"]>20]

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,...,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
4,Group stage,1,Sat,2026-06-13,12:00,Qatar,Switzerland,1–1,1,1,...,11,3,10,8,35,10,7,0.0,1.0,NaN
7,Group stage,1,Sat,2026-06-13,21:00,Australia,Türkiye,2–0,2,0,...,4,5,8,14,26,6,4,1.0,3.0,NaN
9,Group stage,1,Sun,2026-06-14,15:00,Netherlands,Japan,2–2,2,2,...,7,5,4,21,23,7,4,1.0,0.0,NaN
15,Group stage,1,Mon,2026-06-15,18:00,Saudi Arabia,Uruguay,1–1,1,1,...,6,4,14,7,47,7,10,0.0,6.0,NaN
22,Group stage,1,Wed,2026-06-17,19:00,Ghana,Panama,1–0,1,0,...,11,2,2,16,21,8,5,4.0,1.0,NaN
32,Group stage,2,Sat,2026-06-20,12:00,Netherlands,Sweden,5–1,5,1,...,12,2,5,15,21,8,6,3.0,3.0,NaN

In [35]:
df[df["away_crosses"]<20]

,round,gameweek,dayofweek,date,start_time,home_team,away_team,score,home_score,away_score,...,away_fouls,home_corners,away_corners,home_crosses,away_crosses,home_interceptions,away_interceptions,home_offsides,away_offsides,notes
0,Group stage,1,Thu,2026-06-11,13:00,Mexico,South Africa,2–0,2,0,...,11,3,1,12,8,8,7,1.0,1.0,NaN
1,Group stage,1,Thu,2026-06-11,20:00,Korea Republic,Czechia,2–1,2,1,...,16,4,5,12,15,11,7,2.0,2.0,NaN
2,Group stage,1,Fri,2026-06-12,15:00,Canada,Bosnia & Herz.,1–1,1,1,...,20,9,4,24,10,4,10,1.0,0.0,NaN
3,Group stage,1,Fri,2026-06-12,18:00,United States,Paraguay,4–1,4,1,...,17,3,1,17,5,11,9,2.0,1.0,NaN
5,Group stage,1,Sat,2026-06-13,18:00,Brazil,Morocco,1–1,1,1,...,14,6,2,16,15,5,4,0.0,1.0,NaN
6,Group stage,1,Sat,2026-06-13,21:00,Haiti,Scotland,0–1,0,1,...,21,4,3,23,14,6,6,3.0,1.0,NaN
8,Group stage,1,Sun,2026-06-14,12:00,Germany,Curaçao,7–1,7,1,...,11,8,1,12,7,10,16,0.0,1.0,NaN
10,Group stage,1,Sun,2026-06-14,19:00,Côte d'Ivoire,Ecuador,1–0,1,0,...,13,3,5,7,14,11,13,NaN,NaN,NaN
11,Group stage,1,Sun,2026-06-14,20:00,Sweden,Tunisia,5–1,5,1,...,8,4,2,12,13,8,5,3.0,6.0,NaN
12,Group stage,1,Mon,2026-06-15,12:00,Belgium,Egypt,1–1,1,1,...,15,2,7,16,13,10,12,0.0,1.0,NaN
13,Group stage,1,Mon,2026-06-15,12:00,Spain,Cabo Verde,0–0,0,0,...,1,11,1,36,4,6,16,2.0,3.0,NaN
14,Group stage,1,Mon,2026-06-15,18:00,IR Iran,New Zealand,2–2,2,2,...,8,4,1,19,12,11,13,2.0,0.0,NaN
16,Group stage,1,Tue,2026-06-16,15:00,France,Senegal,3–1,3,1,...,9,6,4,9,9,7,8,1.0,3.0,NaN
17,Group stage,1,Tue,2026-06-16,18:00,Iraq,Norway,1–4,1,4,...,13,2,5,13,17,5,3,1.0,0.0,NaN
18,Group stage,1,Tue,2026-06-16,20:00,Argentina,Algeria,3–0,3,0,...,8,2,2,5,8,12,8,3.0,1.0,NaN
19,Group stage,1,Tue,2026-06-16,21:00,Austria,Jordan,3–1,3,1,...,7,4,3,17,15,15,12,3.0,1.0,NaN
20,Group stage,1,Wed,2026-06-17,12:00,Portugal,Congo DR,1–1,1,1,...,10,5,4,23,9,2,5,3.0,2.0,NaN
21,Group stage,1,Wed,2026-06-17,15:00,England,Croatia,4–2,4,2,...,12,8,2,13,13,7,7,0.0,1.0,NaN
23,Group stage,1,Wed,2026-06-17,20:00,Uzbekistan,Colombia,1–3,1,3,...,11,3,4,13,15,7,6,0.0,3.0,NaN
24,Group stage,2,Thu,2026-06-18,12:00,Czechia,South Africa,1–1,1,1,...,10,5,5,16,17,9,9,2.0,3.0,NaN
25,Group stage,2,Thu,2026-06-18,12:00,Switzerland,Bosnia & Herz.,4–1,4,1,...,18,7,3,22,12,4,12,3.0,1.0,NaN
26,Group stage,2,Thu,2026-06-18,15:00,Canada,Qatar,6–0,6,0,...,10,19,1,55,3,6,11,1.0,1.0,NaN
27,Group stage,2,Thu,2026-06-18,19:00,Mexico,Korea Republic,1–0,1,0,...,7,0,2,5,9,7,5,3.0,6.0,NaN
28,Group stage,2,Fri,2026-06-19,12:00,United States,Australia,2–0,2,0,...,16,7,4,14,19,21,7,1.0,0.0,NaN
29,Group stage,2,Fri,2026-06-19,18:00,Scotland,Morocco,0–1,0,1,...,8,2,5,13,10,9,5,1.0,0.0,NaN
30,Group stage,2,Fri,2026-06-19,20:00,Türkiye,Paraguay,0–1,0,1,...,15,12,0,42,6,6,9,2.0,3.0,NaN
31,Group stage,2,Fri,2026-06-19,20:30,Brazil,Haiti,3–0,3,0,...,14,4,4,9,11,10,9,8.0,4.0,NaN
33,Group stage,2,Sat,2026-06-20,16:00,Germany,Côte d'Ivoire,2–1,2,1,...,7,8,3,21,9,7,13,0.0,1.0,NaN
34,Group stage,2,Sat,2026-06-20,19:00,Ecuador,Curaçao,0–0,0,0,...,10,9,0,32,1,7,8,1.0,2.0,NaN
35,Group stage,2,Sat,2026-06-20,22:00,Tunisia,Japan,0–4,0,4,...,15,3,5,10,11,14,6,1.0,1.0,NaN

In [36]:
df.loc[0]

round                               Group stage
gameweek                                      1
dayofweek                                   Thu
date                                 2026-06-11
start_time                                13:00
home_team                                Mexico
away_team                          South Africa
score                                       2–0
home_score                                    2
away_score                                    0
attendance                               80,824
venue                 Estadio Banorte, Coyoacán
referee                          Wilton Sampaio
home_formation                          4-1-4-1
away_formation                            5-3-2
home_manager                     Javier Aguirre
away_manager                         Hugo Broos
home_captain                       César Montes
away_captain                    Ronwen Williams
home_possession                              61
away_possession                              40
home_sot                                      4
away_sot                                      2
home_total_shots                             16
away_total_shots                              3
home_saves                                    2
away_saves                                    2
home_cards_yellow                             1
away_cards_yellow                             2
home_cards_red                                1
away_cards_red                                2
home_fouls                                   12
away_fouls                                   11
home_corners                                  3
away_corners                                  1
home_crosses                                 12
away_crosses                                  8
home_interceptions                            8
away_interceptions                            7
home_offsides                               1.0
away_offsides                               1.0
notes                                       NaN
Name: 0, dtype: object

In [37]:
df.iloc[0]

round                               Group stage
gameweek                                      1
dayofweek                                   Thu
date                                 2026-06-11
start_time                                13:00
home_team                                Mexico
away_team                          South Africa
score                                       2–0
home_score                                    2
away_score                                    0
attendance                               80,824
venue                 Estadio Banorte, Coyoacán
referee                          Wilton Sampaio
home_formation                          4-1-4-1
away_formation                            5-3-2
home_manager                     Javier Aguirre
away_manager                         Hugo Broos
home_captain                       César Montes
away_captain                    Ronwen Williams
home_possession                              61
away_possession                              40
home_sot                                      4
away_sot                                      2
home_total_shots                             16
away_total_shots                              3
home_saves                                    2
away_saves                                    2
home_cards_yellow                             1
away_cards_yellow                             2
home_cards_red                                1
away_cards_red                                2
home_fouls                                   12
away_fouls                                   11
home_corners                                  3
away_corners                                  1
home_crosses                                 12
away_crosses                                  8
home_interceptions                            8
away_interceptions                            7
home_offsides                               1.0
away_offsides                               1.0
notes                                       NaN
Name: 0, dtype: object

In [40]:
df.drop("away_crosses",axis=1, inplace=True)\

KeyError: "['away_crosses'] not found in axis"